# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13gaB9F0xnecCLeb_TYLeBdWBAGVvysnz
"""



import numpy as np
import random as rd

import matplotlib.pyplot as plt

x=np.random.random_integers(0,255,size=(256,256,3))

plt.imshow(x)

np.mean(x)

u=np.mean(x,axis=(0,1))
u.shape

u

y=np.random.random_integers(127.25,127.27,size=(256,256,3))

r=234
g=184
b=149
image=np.zeros((501,501,3),dtype=int);
image[:,:,0]=234;
image[:,:,1]=184;
image[:,:,2]=149;

image

n=plt.imshow(image)
for i in 
r1=255-234
g1=255-184
b1=255-149

image1=np.zeros((501,501,3),dtype=int);
image1[:,:,0]=r1;
image1[:,:,1]=g1;
image1[:,:,2]=b1;

figure, axis = plt.subplots(2, 2)
axis[0, 0].imshow(image1);
axis[0, 1].imshow(image);

def colorcode(i,j,r):
  r1=255-i;
  g=255-j;
  b=255-r;
  num=abs(i+j+r-255*3)
  colours=np.ndarray(shape=(500,500,3,num),dtype=int)
  
  count=0;
  temp=0;



  for x in range(0,256,20):
    for y in range(255,0,-20):
      for z in range(0,256,20):
        if abs(x-i)>60 and abs(y-j)>60 and abs(z-r)>60:
          if abs(temp-abs(((x+y+z)-(i+j+r))))>20 and count<num:
           print(x,y,z);
           colours[:,:,0,count]=x;
           colours[:,:,1,count]=y;
           colours[:,:,2,count]=z;

           count=count+1;
           temp=abs(((x+y+z)-(i+j+r)));

  print(count)
  return colours;

range(step)

col=colorcode(133,90,76)

col[:,:,0,67]

plt.imshow(col[:,:,:,67])

figure, axis = plt.subplots(15, 15);
count=0;
figure.set_figheight(200);
figure.set_figwidth(200);
for i in range(15):
  for j in range(15):
    axis[i,j].imshow(col[:,:,:,count])
    count=count+1;

figure, axis = plt.subplots(10, 10);
count=0;
figure.set_figheight(300);
figure.set_figwidth(300);
for i in range(10):
  for j in range(10):
    axis[i,j].imshow(col[:,:,:,count])
    count=count+1;

image=np.zeros((501,501,3),dtype=int);
image[:,:,0]=133;
image[:,:,1]=90;
image[:,:,2]=76;
plt.imshow(image)